name: CI
on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/ci.yml

concurrency: ${{ github.workflow }}--${{ github.ref }}

jobs:
  main:
    name: Node.js LTS
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Format
        run: bun run format:check

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

      - name: Test
        run: bun run test
